package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/joho/godotenv"
)

var municipi = "08001" // Definim el municipi per defecte per la consulta dels valors climatologics

var apiKey string

func init() {
	err := godotenv.Load()
	if err != nil {
		log.Println("Aviso: No se pudo cargar el archivo .env")
	}
	// Cargar la API key únicamente desde la variable de entorno
	apiKey = os.Getenv("AEMET_API_KEY")
}

// Realitzem una funció per gestionar l'obtenció de les dades climatologiques
func (g *Diaria) GetPrediccions() (*Diaria, error) {
	// Si no se asignó CodiIne, usamos el valor por defecto
	codi := g.CodiIne
	if codi == "" {
		codi = municipi
	}

	result, err := GetPreUrl(codi)
	if err != nil {
		return nil, err
	}
	valors, err := GetPrediccio(result)
	return valors, err
}

func GetPreUrl(codiMunicipi string) (string, error) {
	url := fmt.Sprintf("https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/%s/?api_key=%s", codiMunicipi, apiKey)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return "", fmt.Errorf("error creant la petició HTTP: %w", err)
	}

	req.Header.Add("cache-control", "no-cache")
	req.Header.Set("User-Agent", "EcoHortApp/1.0 (ecohortapp@cibernarium.cat)")

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Println("error contactant amb aemet.es", err)
		return "", err
	}
	defer res.Body.Close()

	body, err := io.ReadAll(res.Body)
	if err != nil {
		log.Println("error llegint el json", err)
		return "", err
	}

	var preUrl PreUrl
	err = json.Unmarshal(body, &preUrl)
	if err != nil {
		log.Println("error unmarshalling", err)
		return "", err
	}

	if preUrl.Url == "" {
		errAemet := fmt.Errorf("AEMET no ha retornat URL. Resposta rebuda: %s", string(body))
		log.Println(errAemet)
		return "", errAemet
	}

	return preUrl.Url, nil
}

func GetPrediccio(url string) (*Diaria, error) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, fmt.Errorf("error creant la petició HTTP: %w", err)
	}

	req.Header.Add("cache-control", "no-cache")
	req.Header.Set("User-Agent", "EcoHortApp/1.0 (ecohortapp@cibernarium.cat)")

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Println("error contactant amb aemet.es", err)
		return nil, err
	}
	defer res.Body.Close()

	body, err := io.ReadAll(res.Body)
	if err != nil {
		log.Println("error llegint el json", err)
		return nil, err
	}

	var prediccio AutoGenerated
	err = json.Unmarshal(body, &prediccio)
	if err != nil {
		log.Println("error unmarshalling", err)
		return nil, err
	}

	// Validació de seguretat per evitar panic per índex fora de rang
	if len(prediccio) == 0 || len(prediccio[0].Prediccion.Dia) == 0 {
		return nil, errors.New("la resposta d'AEMET no conté dades de predicció vàlides")
	}

	diaActual := prediccio[0].Prediccion.Dia[0]

	var precipitacio int
	if len(diaActual.ProbPrecipitacion) > 0 {
		precipitacio = diaActual.ProbPrecipitacion[0].Value
	}

	tempMax := diaActual.Temperatura.Maxima
	tempMin := diaActual.Temperatura.Minima
	humitat := diaActual.HumedadRelativa.Maxima

	currentInfo := Diaria{
		ProbPrecipitacio: precipitacio,
		TemperaturaMax:   tempMax,
		TemperaturaMin:   tempMin,
		HumitatRelativa:  humitat,
		Time:             time.Now(),
	}

	return &currentInfo, nil
}
