package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"time"
)

// CCAATree almacena la relación jerárquica CCAA -> Provincias
type CCAATree map[string][]string

// BuildCCAATree procesa el slice de municipios en RAM y devuelve la jerarquía de regiones ordenada
func BuildCCAATree(municipis []Municipio) (CCAATree, []string) {
	tree := make(CCAATree)
	provSeen := make(map[string]bool)

	for _, m := range municipis {
		if m.CCAA == "" || m.Provincia == "" {
			continue
		}
		key := m.CCAA + "|" + m.Provincia
		if !provSeen[key] {
			provSeen[key] = true
			tree[m.CCAA] = append(tree[m.CCAA], m.Provincia)
		}
	}

	var ccaaKeys []string
	for ccaa, provs := range tree {
		sort.Strings(provs)
		ccaaKeys = append(ccaaKeys, ccaa)
	}
	sort.Strings(ccaaKeys)

	return tree, ccaaKeys
}

// ExecutarDescargaModePro recorre els municipis seleccionats, descarrega d'AEMET i desa la predicció
func (cfg *Config) ExecutarDescargaModePro(onProgress func(actual, total int, nom string)) (int, error) {
	seleccionats := cfg.UserConfig.Municipios
	total := len(seleccionats)
	if total == 0 {
		return 0, fmt.Errorf("no hi ha cap municipi seleccionat al Mode PRO")
	}

	mapaNoms := make(map[string]string)
	for _, m := range cfg.Municipis {
		mapaNoms[m.CodigoINE()] = m.Nombre
	}

	completats := 0
	for i, codiINE := range seleccionats {
		nom := mapaNoms[codiINE]
		if nom == "" {
			nom = codiINE
		}

		if onProgress != nil {
			onProgress(i+1, total, nom)
		}

		endpoint := fmt.Sprintf("https://opendata.aemet.es/opendata/api/prediccion/especifica/municipio/diaria/%s", codiINE)

		rawJSON, err := cfg.ObtenirDadesAEMET(endpoint)
		if err == nil && len(rawJSON) > 0 {
			var resp AutoGenerated
			if err := json.Unmarshal(rawJSON, &resp); err == nil && len(resp) > 0 {
				for _, dia := range resp[0].Prediccion.Dia {
					t, err := time.Parse("2006-01-02T15:04:05", dia.Fecha)
					if err != nil {
						t, _ = time.Parse("2006-01-02", dia.Fecha)
					}

					prob := 0
					if len(dia.ProbPrecipitacion) > 0 {
						prob = dia.ProbPrecipitacion[0].Value
					}

					hum := 0
					if len(dia.HumedadRelativa.Dato) > 0 {
						hum = dia.HumedadRelativa.Dato[0].Value
					} else {
						hum = (dia.HumedadRelativa.Maxima + dia.HumedadRelativa.Minima) / 2
					}

					if cfg.DB != nil {
						_ = cfg.DB.GuardarPrediccioDiaria(codiINE, t.Unix(), prob, dia.Temperatura.Maxima, dia.Temperatura.Minima, hum)
					}
				}
				completats++
			}
		}

		time.Sleep(100 * time.Millisecond)
	}

	return completats, nil
}
