package main

import (
	"ecohortapp/repository"
	"log"
	"net/http"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/widget"
)

// ==============================================================
// Config centraliza las referencias principales de la aplicación
// ==============================================================

// Crearem un struct amb totes les configuracions que necessiti la nostre App
type Config struct {
	App                                fyne.App              //Definim que emprara Fyne per construir la GUI de l'App
	InfoLog                            *log.Logger           //Definim un Log d'accions
	ErrorLog                           *log.Logger           //Definim un Log d'errors
	DB                                 repository.Repository //Definim la referencia a la conexió a SQLite
	MainWindow                         fyne.Window           //Aqui enmagatzemem la referencia a certes arees de la ui per controlar les actualitzacions de les mateixes.
	ClimaDadesContainer                *fyne.Container       //Guardem el contenidor de les dades del clima, referenciant el punter de memòria del contenidor de fyne.
	PronosticGraficContainer           *fyne.Container       //Definim un camp a on enmagatzem el contenidor del gràfic de clima, que ara sera de tipus contenidor fyne
	Registres                          [][]interface{}       //Per emmagatzemar el slice de slices en forma de interfície a on esta contingut les dades obtingudes de la bd
	RegistresTable                     *widget.Table         //Per emmagatzemar la referencia al punter que correspon el widget de la Taula.
	HTTPClient                         http.Client           //Afegim la referència al client http sence necessitat de invocar la llibreria
	AfegirRegistresDataRegistreEntrada *widget.Entry         //Afegim la referencia a la entrada del valor data registre per a nous registres que guardem en la bd
	AfegirRegistresPrecipitacioEntrada *widget.Entry         //Afegim la referencia a la entrada del valor precipitacio per a nous registres que guardem en la bd
	AfegirRegistresTempMaximaEntrada   *widget.Entry         //Afegim la referencia a la entrada del valor tempMaxima per a nous registres que guardem en la bd
	AfegirRegistresTempMinimaEntrada   *widget.Entry         //Afegim la referencia a la entrada del valor tempMinima per a nous registres que guardem en la bd
	AfegirRegistresHumitatEntrada      *widget.Entry         //Afegim la referencia a la entrada del valor humitat per a nous registres que guardem en la bd
	municipi                           string                //Afegim la referencia a aquest valor de configuració
	apiKey                             string                //Afegim la referencia a aquest valor de configuració
	UserConfig                         UserConfig
}

// Estructura per descodificar la primera resposta JSON de la API d'AEMET
type AemetRespuestaAPI struct {
	Descripcion string `json:"descripcion"`
	Estado      int    `json:"estado"`
	Datos       string `json:"datos"`
	Metadatos   string `json:"metadatos"`
}

type Municipio struct {
	ID        string `json:"id"`     // Ej: "id08001"
	IDOld     string `json:"id_old"` // Ej: "08001" (Código INE de 5 dígitos)
	Nombre    string `json:"nombre"` // Ej: "Abrera"
	Longitude string `json:"longitud"`
	Latitude  string `json:"latitud"`
	Altitude  string `json:"altitud"`
	Provincia string `json:"-"` // Calculado según los 2 primeros dígitos de IDOld
	CCAA      string `json:"-"` // Calculado según la provincia
}

// UserConfig define las preferencias del usuario para config.json
type UserConfig struct {
	MunicipioCodigo string   `json:"municipio_codigo"`
	Municipios      []string `json:"municipios"`
}

// Estructures del fitxers clima-valors.go
type PreUrl struct {
	Url    string       `json:"datos"` //Definim que el camp Url sera de tipus igual que el item "datos" del Json obtingut
	Client *http.Client //Aquest camp ens servirà per quan realitzem testing, tindrem enmagatzemat aqui el tipus de crida que s'ha realitzat
}

type AutoGenerated []struct {
	Origen     Origen     `json:"origen"`
	Elaborado  string     `json:"elaborado"`
	Nombre     string     `json:"nombre"`
	Provincia  string     `json:"provincia"`
	Prediccion Prediccion `json:"prediccion"`
	ID         int        `json:"id"`
	Version    float64    `json:"version"`
}
type Origen struct {
	Productor string `json:"productor"`
	Web       string `json:"web"`
	Enlace    string `json:"enlace"`
	Language  string `json:"language"`
	Copyright string `json:"copyright"`
	NotaLegal string `json:"notaLegal"`
}
type ProbPrecipitacion struct {
	Value   int    `json:"value"`
	Periodo string `json:"periodo"`
}
type CotaNieveProv struct {
	Value   string `json:"value"`
	Periodo string `json:"periodo"`
}
type EstadoCielo struct {
	Value       string `json:"value"`
	Periodo     string `json:"periodo"`
	Descripcion string `json:"descripcion"`
}
type Viento struct {
	Direccion string `json:"direccion"`
	Velocidad int    `json:"velocidad"`
	Periodo   string `json:"periodo"`
}
type RachaMax struct {
	Value   string `json:"value"`
	Periodo string `json:"periodo"`
}
type Dato struct {
	Value int `json:"value"`
	Hora  int `json:"hora"`
}
type Temperatura struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type SensTermica struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type HumedadRelativa struct {
	Maxima int    `json:"maxima"`
	Minima int    `json:"minima"`
	Dato   []Dato `json:"dato"`
}
type Dia struct {
	ProbPrecipitacion []ProbPrecipitacion `json:"probPrecipitacion"`
	CotaNieveProv     []CotaNieveProv     `json:"cotaNieveProv"`
	EstadoCielo       []EstadoCielo       `json:"estadoCielo"`
	Viento            []Viento            `json:"viento"`
	RachaMax          []RachaMax          `json:"rachaMax"`
	Temperatura       Temperatura         `json:"temperatura"`
	SensTermica       SensTermica         `json:"sensTermica"`
	HumedadRelativa   HumedadRelativa     `json:"humedadRelativa"`
	UvMax             int                 `json:"uvMax,omitempty"`
	Fecha             string              `json:"fecha"`
}
type Prediccion struct {
	Dia []Dia `json:"dia"`
}
type Diaria struct {
	CodiIne          string    `json:"-"` // Nuevo campo para el código del municipio
	ProbPrecipitacio int       `json:"probPrecipitacion"`
	TemperaturaMax   int       `json:"maxima"`
	TemperaturaMin   int       `json:"minima"`
	HumitatRelativa  int       `json:"humedadRelativa"`
	Time             time.Time `json:"-"`
}
